### PR TITLE
5.1 compatibility

### PR DESCRIPTION
**Pull request by jmfederico**
Draftsman is not compatible with 5.1 series as it is, but small changes are needed that keep it backwards compatible.

I haven't changed `draftsman.gemspec`, but did test locally with 5.1.0.rc2 and all tests pass.

### CODE REVIEW

**Comment by jmfederico** [comment]
Actually, it becomes incompatible with 4 and older versions of Activerecord.
Adding tests againts multiple Activerecord versions

**Comment by jmfederico** [comment]
So, I am already getting my apps ready for Rails 5.1, and wanted to help with Draftsman.

There was only one deprecation that needed attention (parameters), and 1 change (belong_to).

I noticed that Travis tests were being run for different Ruby versions but not for different Activerecord versions.

I implemented separate Gemfiles for 5.0.x and 5.1.x versions.

I hope this is useful.

**Comment by chrisdpeters** [comment]
Thank you, @jmfederico. I'm currently busy on a tangent not related to this right now but will review soon and probably merge.

This also lights a fire under me to update my application to Rails 5. 🔥

**Comment by chrisdpeters** [comment]
@jmfederico Good news... I was able to restore ActiveRecord 4 compatibility. 🎉

**Comment by jmfederico** [comment]
Nice!

**Pull request merged**
