### PR TITLE
Remove reliance on SerializedAttributes due to its removal in Rails 5

### PR DESCRIPTION
**Pull request by npezza93**
Should resolve issue #44 . 
Essentially copied what paper trail had implemented.

### CODE REVIEW

**Comment by chrisdpeters** [comment]
@npezza93 Thank you for this. Have you had a chance to run Draftsman within a Rails 5 beta app yet?

**Comment by npezza93** [comment]
I have and didn't have any issues. I swapped all the `before_filter`s for `before_action` too since it will be removed in Rails 5.1

**Comment by lukad03** [comment]
Any updates on this @chrisdpeters? Thanks!

**Comment by chrisdpeters** [comment]
@lukad03 I'll get this merged and released this week. I've been dragging my feet on upgrading my app to Rails 5, but that shouldn't be an excuse for holding this up!

**Comment by lukad03** [comment]
@chrisdpeters Perfect! Thanks for the update and all of your excellent work 👍

**Comment by chrisdpeters** [comment]
@npezza93 Thank you for this huge contribution.

@lukad03 Thanks again for nudging me. :D

**Pull request merged**
