### PR TITLE
Resubmitting #14 - Adding callbacks for draft creation, update, and destroy

### PR DESCRIPTION
**Pull request by npafundi**
See discussion and comments at [#14](https://github.com/liveeditor/draftsman/pull/14)

### CODE REVIEW

**Comment by npafundi** [comment]
Hey @chrisdpeters, thanks for merging #21 and #23.  If you'd like, I can rebase this and make sure it's a clean fast forward merge.

**Comment by chrisdpeters** [comment]
@npafundi No worries. I will be releasing v0.3.4 with your bug fixes soon. These new callbacks will go in v0.4.

**Comment by npafundi** [comment]
@chrisdpeters I rebased this branch to match master again.  Are you still considering pulling this in?

**Comment by chrisdpeters** [comment]
@npafundi Thank you for the rebase. Yes, I would like to get this merged and released within a week or 2. I wanted to spend some time reviewing the tests just to make sure I understand everything fully. I'm sure it's fairly straightforward.

**Comment by chrisdpeters** [comment]
@npafundi Heck, let's merge now. This is next on the list.

**Comment by npafundi** [comment]
Thanks @chrisdpeters!  Happy to explain anything, and if I'm missing any tests we can definitely add more.

**Pull request merged**
